package goalpr

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Meaningful product CI check names installed by LoopCoder on disposable repos.
// These must run real tests against the PR head, not README/echo smoke.
const (
	CheckProductTests = "product-tests"
	CheckProductBuild = "product-build"
)

// MeaningfulCheckNames is the required set for product canaries.
func MeaningfulCheckNames() []string {
	return []string{CheckProductTests, CheckProductBuild}
}

// InstallMeaningfulCI writes a GitHub Actions workflow that runs product tests
// on the PR head (go test when go.mod present; otherwise fail closed if no
// test harness). Returns relative paths written.
func InstallMeaningfulCI(repoPath string) (written []string, err error) {
	repoPath = strings.TrimSpace(repoPath)
	if repoPath == "" {
		return nil, fmt.Errorf("%w: repo required", ErrInvalid)
	}
	wfDir := filepath.Join(repoPath, ".github", "workflows")
	if err := os.MkdirAll(wfDir, 0o755); err != nil {
		return nil, err
	}
	// Detect product language for test command.
	testCmd := detectProductTestCommand(repoPath)
	body := fmt.Sprintf(`# Generated by LoopCoder goalpr — product required checks (not README/echo).
name: loopcoder-product
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  product-tests:
    name: %s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: detect product
        id: det
        run: |
          set -euo pipefail
          if [ -f go.mod ]; then echo "kind=go" >> "$GITHUB_OUTPUT"
          elif [ -f package.json ]; then echo "kind=node" >> "$GITHUB_OUTPUT"
          elif [ -f pyproject.toml ] || [ -f requirements.txt ]; then echo "kind=py" >> "$GITHUB_OUTPUT"
          else echo "kind=unknown" >> "$GITHUB_OUTPUT"
          fi
      - name: setup go
        if: steps.det.outputs.kind == 'go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: run product tests
        run: |
          set -euo pipefail
          %s
  product-build:
    name: %s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: product tree must not be receipt-only
        run: |
          set -euo pipefail
          # Fail if only .loopcoder / README / workflow files exist.
          product=$(find . -type f \
            ! -path './.git/*' \
            ! -path './.loopcoder/*' \
            ! -path './.github/*' \
            ! -name 'README.md' \
            ! -name 'LICENSE' | head -20)
          if [ -z "$product" ]; then
            echo "receipt-only tree: no product files on PR head" >&2
            exit 1
          fi
          echo "product files present:"
          echo "$product"
      - name: compile when go
        if: hashFiles('go.mod') != ''
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: go build
        if: hashFiles('go.mod') != ''
        run: go build ./...
`, CheckProductTests, testCmd, CheckProductBuild)

	path := filepath.Join(wfDir, "loopcoder-product.yml")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return nil, err
	}
	rel := filepath.ToSlash(filepath.Join(".github", "workflows", "loopcoder-product.yml"))
	return []string{rel}, nil
}

func detectProductTestCommand(repoPath string) string {
	if _, err := os.Stat(filepath.Join(repoPath, "go.mod")); err == nil {
		return `go test ./...
          # Require at least one *_test.go under product paths (not only meta).
          if ! find . -name '*_test.go' ! -path './.git/*' ! -path './.loopcoder/*' | grep -q .; then
            echo "no *_test.go product tests on head" >&2
            exit 1
          fi`
	}
	if _, err := os.Stat(filepath.Join(repoPath, "package.json")); err == nil {
		return `npm test --if-present
          if [ ! -f package.json ]; then exit 1; fi`
	}
	if _, err := os.Stat(filepath.Join(repoPath, "pyproject.toml")); err == nil {
		return `python -m pytest -q || python -m unittest discover -q`
	}
	// Fail closed: no known harness — still require product files + a tests/ or *_test.*
	return `echo "unknown harness; requiring product test files"
          if ! find . \( -name '*_test.go' -o -name 'test_*.py' -o -name '*.test.js' -o -path '*/tests/*' \) \
            ! -path './.git/*' ! -path './.loopcoder/*' | grep -q .; then
            echo "no product tests found on PR head" >&2
            exit 1
          fi
          echo "product test files present (harness unknown — structural gate only)"`
}

// IsMeaningfulCheck reports whether a check name is a product gate (not smoke).
func IsMeaningfulCheck(name string) bool {
	n := strings.ToLower(strings.TrimSpace(name))
	switch n {
	case strings.ToLower(CheckProductTests), strings.ToLower(CheckProductBuild):
		return true
	}
	// Accept job names that contain product-tests / go test signals.
	if strings.Contains(n, "product-test") || strings.Contains(n, "product-build") {
		return true
	}
	// Reject known-useless patterns.
	if n == "verify" || n == "test" || strings.Contains(n, "echo") || strings.Contains(n, "readme") {
		return false
	}
	return false
}
