package storage

var acceptedTaskGraphSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS task_graph_validations (
		task_graph_validation_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT NOT NULL REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		plan_fingerprint TEXT NOT NULL,
		authorization_fingerprint TEXT NOT NULL,
		validation_status TEXT NOT NULL,
		error_code TEXT NOT NULL DEFAULT '',
		validation_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		created_by_json TEXT NOT NULL,
		host_json TEXT NOT NULL,
		CHECK(json_valid(validation_json)),
		CHECK(json_valid(created_by_json)),
		CHECK(json_valid(host_json))
	)`,
	`CREATE INDEX IF NOT EXISTS idx_task_graph_validations_run ON task_graph_validations(project_id, delivery_run_id, plan_fingerprint)`,
	`CREATE TABLE IF NOT EXISTS accepted_task_graph_versions (
		graph_version_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT NOT NULL REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		input_fingerprint TEXT NOT NULL,
		policy_fingerprint TEXT NOT NULL,
		plan_fingerprint TEXT NOT NULL,
		authorization_fingerprint TEXT NOT NULL,
		policy_version TEXT NOT NULL,
		routing_policy_profile_id TEXT NOT NULL,
		routing_policy_profile_fingerprint TEXT NOT NULL,
		task_graph_validation_id TEXT NOT NULL REFERENCES task_graph_validations(task_graph_validation_id),
		approval_id TEXT NOT NULL DEFAULT '',
		task_count INTEGER NOT NULL,
		edge_count INTEGER NOT NULL,
		graph_fingerprint TEXT NOT NULL,
		canonical_proposal_hash TEXT NOT NULL,
		proposal_json TEXT NOT NULL,
		accepted_at TEXT NOT NULL,
		accepted_by_json TEXT NOT NULL,
		host_json TEXT NOT NULL,
		CHECK(json_valid(proposal_json)),
		CHECK(json_valid(accepted_by_json)),
		CHECK(json_valid(host_json)),
		UNIQUE(project_id, delivery_run_id),
		UNIQUE(project_id, delivery_run_id, authorization_fingerprint)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_accepted_task_graph_versions_plan ON accepted_task_graph_versions(project_id, plan_fingerprint)`,
}
