package storage

var agentFederationSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS agent_scope_grants (
		id TEXT PRIMARY KEY,
		project_id TEXT NOT NULL,
		delivery_run_id TEXT NOT NULL,
		child_agent_id TEXT NOT NULL,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL,
		scope_json TEXT NOT NULL,
		permission TEXT NOT NULL,
		side_effect_class TEXT NOT NULL,
		policy_version TEXT NOT NULL,
		policy_fingerprint TEXT NOT NULL,
		plan_fingerprint TEXT NOT NULL,
		authorization_fingerprint TEXT NOT NULL DEFAULT '',
		agent_federation_fingerprint TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		terminal_error_code TEXT NOT NULL DEFAULT ''
	)`,
	`CREATE INDEX IF NOT EXISTS idx_agent_scope_grants_child_agent ON agent_scope_grants(child_agent_id)`,
	`CREATE TABLE IF NOT EXISTS agent_registrations (
		id TEXT PRIMARY KEY,
		project_id TEXT NOT NULL,
		delivery_run_id TEXT NOT NULL,
		root_run_id TEXT NOT NULL,
		parent_run_id TEXT NOT NULL,
		child_run_id TEXT NOT NULL,
		parent_agent_id TEXT NOT NULL DEFAULT '',
		task_id TEXT NOT NULL,
		attempt_id TEXT NOT NULL,
		plan_id TEXT NOT NULL,
		child_key TEXT NOT NULL,
		adapter_id TEXT NOT NULL,
		provider_installation_id TEXT NOT NULL DEFAULT '',
		account_profile_id TEXT NOT NULL DEFAULT '',
		model_capability_id TEXT NOT NULL DEFAULT '',
		routing_decision_id TEXT NOT NULL DEFAULT '',
		provider_session_ref TEXT NOT NULL DEFAULT '',
		scope_grant_id TEXT NOT NULL,
		permission TEXT NOT NULL,
		side_effect_class TEXT NOT NULL,
		claim_generation INTEGER NOT NULL,
		executor_id TEXT NOT NULL,
		provider_idempotency_key TEXT NOT NULL,
		provider_receipt TEXT NOT NULL DEFAULT '',
		cancellation_channel TEXT NOT NULL,
		expected_outputs_json TEXT NOT NULL,
		registration_state TEXT NOT NULL,
		policy_version TEXT NOT NULL,
		plan_fingerprint TEXT NOT NULL,
		policy_fingerprint TEXT NOT NULL,
		authorization_fingerprint TEXT NOT NULL DEFAULT '',
		agent_federation_fingerprint TEXT NOT NULL,
		registration_hash TEXT NOT NULL,
		classification TEXT NOT NULL DEFAULT 'internal',
		gap_reasons_json TEXT NOT NULL DEFAULT '[]',
		depth INTEGER NOT NULL DEFAULT 0,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		terminal_error_code TEXT NOT NULL DEFAULT '',
		UNIQUE(project_id, delivery_run_id, parent_run_id, child_key),
		UNIQUE(child_run_id),
		FOREIGN KEY(scope_grant_id) REFERENCES agent_scope_grants(id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_agent_registrations_root_run ON agent_registrations(root_run_id)`,
	`CREATE INDEX IF NOT EXISTS idx_agent_registrations_child_agent ON agent_registrations(id)`,
	`CREATE TABLE IF NOT EXISTS agent_ownership_locks (
		id TEXT PRIMARY KEY,
		project_id TEXT NOT NULL,
		delivery_run_id TEXT NOT NULL,
		child_agent_id TEXT NOT NULL,
		run_id TEXT NOT NULL,
		claim_generation INTEGER NOT NULL,
		lock_generation INTEGER NOT NULL,
		resource_kind TEXT NOT NULL,
		resource_key TEXT NOT NULL,
		lock_mode TEXT NOT NULL,
		state TEXT NOT NULL,
		lease_expires_at TEXT NOT NULL,
		heartbeat_at TEXT NOT NULL,
		conflicts_with_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(project_id, resource_kind, resource_key, state)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_agent_ownership_locks_child_agent ON agent_ownership_locks(child_agent_id)`,
	`CREATE TABLE IF NOT EXISTS agent_budget_bindings (
		id TEXT PRIMARY KEY,
		project_id TEXT NOT NULL,
		delivery_run_id TEXT NOT NULL,
		child_agent_id TEXT NOT NULL,
		budget_policy_id TEXT NOT NULL,
		budget_reservation_id TEXT NOT NULL,
		reservation_scope TEXT NOT NULL,
		reserved_quantities_json TEXT NOT NULL,
		ancestor_budget_refs_json TEXT NOT NULL,
		reservation_state TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(child_agent_id, budget_policy_id, budget_reservation_id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_agent_budget_bindings_child_agent ON agent_budget_bindings(child_agent_id)`,
	`CREATE TABLE IF NOT EXISTS agent_events (
		id TEXT PRIMARY KEY,
		project_id TEXT NOT NULL,
		delivery_run_id TEXT NOT NULL,
		child_agent_id TEXT NOT NULL,
		event_kind TEXT NOT NULL,
		event_hash TEXT NOT NULL,
		previous_event_hash TEXT NOT NULL DEFAULT '',
		payload_hash TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_agent_events_child_agent ON agent_events(child_agent_id)`,
}
