package storage

var budgetSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS budget_policies (
		budget_policy_id TEXT PRIMARY KEY,
		project_id TEXT NOT NULL DEFAULT '',
		delivery_run_id TEXT NOT NULL DEFAULT '',
		task_id TEXT NOT NULL DEFAULT '',
		worker_id TEXT NOT NULL DEFAULT '',
		sub_agent_id TEXT NOT NULL DEFAULT '',
		adapter_id TEXT NOT NULL DEFAULT '',
		account_profile_id TEXT NOT NULL DEFAULT '',
		model_capability_id TEXT NOT NULL DEFAULT '',
		scope_kind TEXT NOT NULL,
		scope_key TEXT NOT NULL,
		quantity_kind TEXT NOT NULL,
		unit TEXT NOT NULL,
		value_scale INTEGER NOT NULL DEFAULT 0,
		window_kind TEXT NOT NULL,
		policy_mode TEXT NOT NULL,
		overflow_behavior TEXT NOT NULL DEFAULT '',
		ceiling_value INTEGER NOT NULL,
		active INTEGER NOT NULL DEFAULT 1,
		policy_version TEXT NOT NULL,
		parent_budget_policy_ids_json TEXT NOT NULL DEFAULT '[]',
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(parent_budget_policy_ids_json)),
		CHECK(json_valid(payload_json)),
		CHECK(ceiling_value >= 0),
		CHECK(value_scale >= 0)
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_budget_policies_scope_quantity ON budget_policies(scope_key, quantity_kind, window_kind, policy_version)`,
	`CREATE INDEX IF NOT EXISTS idx_budget_policies_project_scope ON budget_policies(project_id, delivery_run_id, task_id, worker_id, sub_agent_id)`,
	`CREATE INDEX IF NOT EXISTS idx_budget_policies_provider_scope ON budget_policies(adapter_id, account_profile_id, model_capability_id)`,
	`CREATE TABLE IF NOT EXISTS budget_aggregates (
		budget_policy_id TEXT PRIMARY KEY REFERENCES budget_policies(budget_policy_id) ON DELETE RESTRICT,
		reserved_value INTEGER NOT NULL DEFAULT 0,
		committed_value INTEGER NOT NULL DEFAULT 0,
		record_version INTEGER NOT NULL DEFAULT 1,
		updated_at TEXT NOT NULL,
		CHECK(reserved_value >= 0),
		CHECK(committed_value >= 0),
		CHECK(record_version > 0)
	)`,
	`CREATE TABLE IF NOT EXISTS budget_reservations (
		budget_reservation_id TEXT PRIMARY KEY,
		idempotency_key TEXT NOT NULL,
		request_fingerprint TEXT NOT NULL,
		requester_id TEXT NOT NULL DEFAULT '',
		authorization_fingerprint TEXT NOT NULL DEFAULT '',
		project_id TEXT NOT NULL DEFAULT '',
		delivery_run_id TEXT NOT NULL DEFAULT '',
		task_id TEXT NOT NULL DEFAULT '',
		worker_id TEXT NOT NULL DEFAULT '',
		sub_agent_id TEXT NOT NULL DEFAULT '',
		adapter_id TEXT NOT NULL DEFAULT '',
		account_profile_id TEXT NOT NULL DEFAULT '',
		model_capability_id TEXT NOT NULL DEFAULT '',
		quantity_kind TEXT NOT NULL,
		unit TEXT NOT NULL,
		value_scale INTEGER NOT NULL DEFAULT 0,
		requested_value INTEGER NOT NULL,
		reserved_value INTEGER NOT NULL,
		committed_value INTEGER NOT NULL DEFAULT 0,
		released_value INTEGER NOT NULL DEFAULT 0,
		state TEXT NOT NULL,
		generation INTEGER NOT NULL DEFAULT 1,
		lease_expires_at TEXT NOT NULL,
		scope_key TEXT NOT NULL,
		policy_ids_json TEXT NOT NULL DEFAULT '[]',
		source_estimate_usage_record_ids_json TEXT NOT NULL DEFAULT '[]',
		commit_usage_record_ids_json TEXT NOT NULL DEFAULT '[]',
		release_usage_record_ids_json TEXT NOT NULL DEFAULT '[]',
		payload_json TEXT NOT NULL DEFAULT '{}',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		CHECK(json_valid(policy_ids_json)),
		CHECK(json_valid(source_estimate_usage_record_ids_json)),
		CHECK(json_valid(commit_usage_record_ids_json)),
		CHECK(json_valid(release_usage_record_ids_json)),
		CHECK(json_valid(payload_json)),
		CHECK(requested_value >= 0),
		CHECK(reserved_value >= 0),
		CHECK(committed_value >= 0),
		CHECK(released_value >= 0),
		CHECK(generation > 0)
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_budget_reservations_idempotency ON budget_reservations(idempotency_key)`,
	`CREATE INDEX IF NOT EXISTS idx_budget_reservations_state_expiry ON budget_reservations(state, lease_expires_at)`,
	`CREATE INDEX IF NOT EXISTS idx_budget_reservations_project_scope ON budget_reservations(project_id, delivery_run_id, task_id, worker_id, sub_agent_id)`,
	`CREATE TABLE IF NOT EXISTS quota_budget_events (
		event_id TEXT PRIMARY KEY,
		idempotency_key TEXT NOT NULL,
		budget_reservation_id TEXT NOT NULL DEFAULT '',
		budget_policy_id TEXT NOT NULL DEFAULT '',
		event_kind TEXT NOT NULL,
		generation INTEGER NOT NULL,
		delta_reserved INTEGER NOT NULL DEFAULT 0,
		delta_committed INTEGER NOT NULL DEFAULT 0,
		event_time TEXT NOT NULL,
		actor_json TEXT NOT NULL DEFAULT '{}',
		host_json TEXT NOT NULL DEFAULT '{}',
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(actor_json)),
		CHECK(json_valid(host_json)),
		CHECK(json_valid(payload_json)),
		CHECK(generation > 0)
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_quota_budget_events_idempotency ON quota_budget_events(idempotency_key)`,
	`CREATE INDEX IF NOT EXISTS idx_quota_budget_events_reservation ON quota_budget_events(budget_reservation_id, event_kind)`,
	`CREATE INDEX IF NOT EXISTS idx_quota_budget_events_policy ON quota_budget_events(budget_policy_id, event_time)`,
}
