package storage

var detachedRunSupervisorSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS detached_run_supervisors (
		run_id TEXT PRIMARY KEY,
		project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		supervisor_owner TEXT NOT NULL,
		supervisor_generation INTEGER NOT NULL,
		launch_phase TEXT NOT NULL,
		status TEXT NOT NULL,
		classification TEXT NOT NULL,
		issue_number INTEGER NOT NULL DEFAULT 0,
		attempt INTEGER NOT NULL DEFAULT 0,
		base_branch TEXT NOT NULL DEFAULT '',
		branch TEXT NOT NULL DEFAULT '',
		provider TEXT NOT NULL DEFAULT '',
		model TEXT NOT NULL DEFAULT '',
		effort TEXT NOT NULL DEFAULT '',
		process_pid INTEGER NOT NULL DEFAULT 0,
		process_authority TEXT NOT NULL DEFAULT '',
		receipt_policy TEXT NOT NULL DEFAULT '',
		delivery_sinks_json TEXT NOT NULL DEFAULT '[]',
		cancellation_channel TEXT NOT NULL DEFAULT '',
		worker_lease_json TEXT NOT NULL DEFAULT '{}',
		recovery_evidence_json TEXT NOT NULL DEFAULT '[]',
		clocks_json TEXT NOT NULL DEFAULT '{}',
		provider_exposed INTEGER NOT NULL DEFAULT 0,
		launch_receipt_id TEXT NOT NULL DEFAULT '',
		terminal_receipt_id TEXT NOT NULL DEFAULT '',
		cancel_requested_at TEXT NOT NULL DEFAULT '',
		claimed_at TEXT NOT NULL,
		lease_expires_at TEXT NOT NULL,
		heartbeat_at TEXT NOT NULL,
		process_started_at TEXT NOT NULL DEFAULT '',
		worker_started_at TEXT NOT NULL DEFAULT '',
		terminal_at TEXT NOT NULL DEFAULT '',
		terminal_error_code TEXT NOT NULL DEFAULT '',
		terminal_error TEXT NOT NULL DEFAULT '',
		payload_json TEXT NOT NULL DEFAULT '{}',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(supervisor_generation > 0),
		CHECK(issue_number >= 0),
		CHECK(attempt >= 0),
		CHECK(process_pid >= 0),
		CHECK(provider_exposed IN (0, 1)),
		CHECK(json_valid(delivery_sinks_json)),
		CHECK(json_valid(worker_lease_json)),
		CHECK(json_valid(recovery_evidence_json)),
		CHECK(json_valid(clocks_json)),
		CHECK(json_valid(payload_json))
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_detached_run_supervisors_owner_generation
		ON detached_run_supervisors(run_id, supervisor_owner, supervisor_generation)`,
	`CREATE INDEX IF NOT EXISTS idx_detached_run_supervisors_status
		ON detached_run_supervisors(project_id, status, launch_phase, lease_expires_at)`,
	`CREATE INDEX IF NOT EXISTS idx_detached_run_supervisors_process
		ON detached_run_supervisors(process_pid, status)`,
}
