package storage

var fallbackReplanSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS fallback_decisions (
		fallback_decision_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT NOT NULL REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		task_id TEXT NOT NULL,
		routing_decision_id TEXT NOT NULL REFERENCES routing_decisions(routing_decision_id) ON DELETE CASCADE,
		fallback_ordinal INTEGER NOT NULL,
		idempotency_key TEXT NOT NULL,
		trigger TEXT NOT NULL,
		prior_candidate_id TEXT NOT NULL,
		fallback_candidate_id TEXT NOT NULL DEFAULT '',
		decision_status TEXT NOT NULL,
		terminal_error_code TEXT NOT NULL DEFAULT '',
		routing_fingerprint TEXT NOT NULL,
		original_candidate_id TEXT NOT NULL DEFAULT '',
		selected_candidate_id TEXT NOT NULL DEFAULT '',
		bounds_remaining INTEGER NOT NULL DEFAULT 0,
		approval_required INTEGER NOT NULL DEFAULT 0,
		legality_results_json TEXT NOT NULL DEFAULT '[]',
		attempt_lineage_json TEXT NOT NULL DEFAULT '[]',
		changed_authority_inputs_json TEXT NOT NULL DEFAULT '[]',
		payload_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		decided_by_json TEXT NOT NULL,
		host_json TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(fallback_ordinal > 0),
		CHECK(bounds_remaining >= 0),
		CHECK(approval_required IN (0, 1)),
		CHECK(json_valid(legality_results_json)),
		CHECK(json_valid(attempt_lineage_json)),
		CHECK(json_valid(changed_authority_inputs_json)),
		CHECK(json_valid(payload_json)),
		CHECK(json_valid(decided_by_json)),
		CHECK(json_valid(host_json)),
		UNIQUE(routing_decision_id, fallback_ordinal),
		UNIQUE(routing_decision_id, idempotency_key)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_fallback_decisions_route ON fallback_decisions(routing_decision_id, fallback_ordinal)`,
	`CREATE INDEX IF NOT EXISTS idx_fallback_decisions_run ON fallback_decisions(project_id, delivery_run_id, task_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS idx_fallback_decisions_status ON fallback_decisions(decision_status, terminal_error_code)`,
	`CREATE TABLE IF NOT EXISTS replan_decisions (
		replan_decision_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT NOT NULL REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		routing_decision_id TEXT NOT NULL DEFAULT '',
		replan_ordinal INTEGER NOT NULL,
		idempotency_key TEXT NOT NULL,
		trigger TEXT NOT NULL,
		prior_plan_fingerprint TEXT NOT NULL,
		new_plan_fingerprint TEXT NOT NULL DEFAULT '',
		routing_fingerprint TEXT NOT NULL DEFAULT '',
		bounds_remaining INTEGER NOT NULL DEFAULT 0,
		approval_required INTEGER NOT NULL DEFAULT 0,
		decision_status TEXT NOT NULL,
		terminal_error_code TEXT NOT NULL DEFAULT '',
		changed_authority_inputs_json TEXT NOT NULL DEFAULT '[]',
		attempt_lineage_json TEXT NOT NULL DEFAULT '[]',
		payload_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		decided_by_json TEXT NOT NULL,
		host_json TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(replan_ordinal > 0),
		CHECK(bounds_remaining >= 0),
		CHECK(approval_required IN (0, 1)),
		CHECK(json_valid(changed_authority_inputs_json)),
		CHECK(json_valid(attempt_lineage_json)),
		CHECK(json_valid(payload_json)),
		CHECK(json_valid(decided_by_json)),
		CHECK(json_valid(host_json)),
		UNIQUE(delivery_run_id, replan_ordinal),
		UNIQUE(delivery_run_id, idempotency_key)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_replan_decisions_run ON replan_decisions(project_id, delivery_run_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS idx_replan_decisions_route ON replan_decisions(routing_decision_id)`,
	`CREATE INDEX IF NOT EXISTS idx_replan_decisions_status ON replan_decisions(decision_status, terminal_error_code)`,
}
