package storage

var handoffSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS handoff_transactions (
		handoff_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT NOT NULL REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		task_id TEXT NOT NULL,
		child_run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
		parent_run_id TEXT NOT NULL,
		source_attempt_id TEXT NOT NULL,
		source_executor_id TEXT NOT NULL,
		source_claim_generation INTEGER NOT NULL,
		source_claim_snapshot_json TEXT NOT NULL,
		trigger_kind TEXT NOT NULL,
		reason_codes_json TEXT NOT NULL,
		evidence_record_ids_json TEXT NOT NULL DEFAULT '[]',
		trigger_snapshot_json TEXT NOT NULL,
		policy_version TEXT NOT NULL,
		input_fingerprint TEXT NOT NULL DEFAULT '',
		policy_fingerprint TEXT NOT NULL DEFAULT '',
		plan_fingerprint TEXT NOT NULL DEFAULT '',
		authorization_fingerprint TEXT NOT NULL DEFAULT '',
		accepted_task_fingerprint TEXT NOT NULL,
		accepted_task_snapshot_json TEXT NOT NULL,
		side_effect_state TEXT NOT NULL,
		destination_route_placeholder TEXT NOT NULL,
		destination_executor_id TEXT NOT NULL,
		destination_claim_generation INTEGER NOT NULL,
		handoff_generation INTEGER NOT NULL,
		handoff_status TEXT NOT NULL,
		next_action TEXT NOT NULL,
		request_fingerprint TEXT NOT NULL,
		idempotency_key TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(source_claim_generation > 0),
		CHECK(destination_claim_generation > source_claim_generation),
		CHECK(handoff_generation = destination_claim_generation),
		CHECK(json_valid(source_claim_snapshot_json)),
		CHECK(json_valid(reason_codes_json)),
		CHECK(json_valid(evidence_record_ids_json)),
		CHECK(json_valid(trigger_snapshot_json)),
		CHECK(json_valid(accepted_task_snapshot_json)),
		CHECK(handoff_status IN ('transferred', 'needs-human', 'blocked'))
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_handoff_task_generation ON handoff_transactions(project_id, delivery_run_id, task_id, handoff_generation)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_handoff_source_attempt ON handoff_transactions(project_id, delivery_run_id, task_id, source_attempt_id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_handoff_idempotency ON handoff_transactions(project_id, delivery_run_id, idempotency_key)`,
	`CREATE INDEX IF NOT EXISTS idx_handoff_task_status ON handoff_transactions(project_id, delivery_run_id, task_id, handoff_status)`,
}
