package storage

var progressDeliveryOutboxSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS progress_delivery_obligations (
		obligation_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
		delivery_run_id TEXT NOT NULL,
		progress_receipt_id TEXT NOT NULL REFERENCES progress_receipts(progress_receipt_id) ON DELETE CASCADE,
		semantic_identity TEXT NOT NULL,
		origin_kind TEXT NOT NULL,
		origin_id TEXT NOT NULL,
		sink_kind TEXT NOT NULL,
		sink_id TEXT NOT NULL,
		transport_contract TEXT NOT NULL,
		status TEXT NOT NULL,
		claim_owner TEXT NOT NULL DEFAULT '',
		claim_generation INTEGER NOT NULL DEFAULT 0,
		claimed_at TEXT NOT NULL DEFAULT '',
		claim_expires_at TEXT NOT NULL DEFAULT '',
		attempt_count INTEGER NOT NULL DEFAULT 0,
		max_attempts INTEGER NOT NULL DEFAULT 3,
		next_attempt_at TEXT NOT NULL DEFAULT '',
		ack_policy TEXT NOT NULL DEFAULT 'required-ack',
		required_ack INTEGER NOT NULL DEFAULT 1,
		expires_at TEXT NOT NULL DEFAULT '',
		superseded_by_obligation_id TEXT REFERENCES progress_delivery_obligations(obligation_id) ON DELETE SET NULL,
		last_error_code TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(claim_generation >= 0),
		CHECK(attempt_count >= 0),
		CHECK(max_attempts > 0),
		CHECK(ack_policy IN ('required-ack', 'no-ack')),
		CHECK(required_ack IN (0, 1)),
		CHECK(status IN ('pending', 'attempting', 'needs-reconciliation', 'delivered-unacknowledged', 'acknowledged', 'unsupported', 'retryable-failure', 'terminal-failure', 'expired', 'superseded')),
		CHECK(json_valid(payload_json)),
		UNIQUE(project_id, delivery_run_id, semantic_identity)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_progress_delivery_obligations_receipt
		ON progress_delivery_obligations(project_id, delivery_run_id, progress_receipt_id)`,
	`CREATE INDEX IF NOT EXISTS idx_progress_delivery_obligations_claim
		ON progress_delivery_obligations(project_id, delivery_run_id, status, next_attempt_at, claim_expires_at, claim_owner, claim_generation)`,
	`CREATE INDEX IF NOT EXISTS idx_progress_delivery_obligations_sink
		ON progress_delivery_obligations(project_id, delivery_run_id, sink_kind, sink_id, status)`,

	`CREATE TABLE IF NOT EXISTS progress_delivery_attempts (
		attempt_record_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
		delivery_run_id TEXT NOT NULL,
		obligation_id TEXT NOT NULL REFERENCES progress_delivery_obligations(obligation_id) ON DELETE CASCADE,
		attempt_ordinal INTEGER NOT NULL,
		claim_owner TEXT NOT NULL,
		claim_generation INTEGER NOT NULL,
		transport_contract TEXT NOT NULL,
		provider_idempotency_key TEXT NOT NULL,
		result_status TEXT NOT NULL DEFAULT '',
		next_attempt_at TEXT NOT NULL DEFAULT '',
		evidence_kind TEXT NOT NULL DEFAULT '',
		evidence_ref TEXT NOT NULL DEFAULT '',
		evidence_json TEXT NOT NULL DEFAULT '{}',
		error_code TEXT NOT NULL DEFAULT '',
		prepared_at TEXT NOT NULL,
		started_at TEXT NOT NULL DEFAULT '',
		completed_at TEXT NOT NULL DEFAULT '',
		payload_json TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(attempt_ordinal > 0),
		CHECK(claim_generation > 0),
		CHECK(result_status = '' OR result_status IN ('delivered-unacknowledged', 'unsupported', 'retryable-failure', 'terminal-failure', 'expired', 'superseded')),
		CHECK(json_valid(evidence_json)),
		CHECK(json_valid(payload_json)),
		UNIQUE(obligation_id, attempt_ordinal),
		UNIQUE(obligation_id, claim_owner, claim_generation),
		UNIQUE(provider_idempotency_key)
	)`,
	`CREATE TABLE IF NOT EXISTS progress_delivery_attempt_results (
		result_record_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
		delivery_run_id TEXT NOT NULL,
		obligation_id TEXT NOT NULL REFERENCES progress_delivery_obligations(obligation_id) ON DELETE CASCADE,
		attempt_record_id TEXT NOT NULL REFERENCES progress_delivery_attempts(attempt_record_id) ON DELETE CASCADE,
		attempt_ordinal INTEGER NOT NULL,
		claim_owner TEXT NOT NULL,
		claim_generation INTEGER NOT NULL,
		transport_contract TEXT NOT NULL,
		provider_idempotency_key TEXT NOT NULL,
		result_status TEXT NOT NULL,
		next_attempt_at TEXT NOT NULL DEFAULT '',
		evidence_kind TEXT NOT NULL,
		evidence_ref TEXT NOT NULL,
		evidence_json TEXT NOT NULL,
		error_code TEXT NOT NULL DEFAULT '',
		started_at TEXT NOT NULL,
		completed_at TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(attempt_ordinal > 0),
		CHECK(claim_generation > 0),
		CHECK(result_status IN ('delivered-unacknowledged', 'unsupported', 'retryable-failure', 'terminal-failure', 'expired', 'superseded')),
		CHECK(json_valid(evidence_json)),
		CHECK(json_valid(payload_json)),
		UNIQUE(attempt_record_id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_progress_delivery_attempts_obligation
		ON progress_delivery_attempts(project_id, delivery_run_id, obligation_id, attempt_ordinal)`,
	`CREATE INDEX IF NOT EXISTS idx_progress_delivery_attempts_claim
		ON progress_delivery_attempts(project_id, delivery_run_id, claim_owner, claim_generation)`,
	`CREATE INDEX IF NOT EXISTS idx_progress_delivery_attempt_results_obligation
		ON progress_delivery_attempt_results(project_id, delivery_run_id, obligation_id, attempt_ordinal)`,

	`CREATE TABLE IF NOT EXISTS progress_delivery_acknowledgments (
		acknowledgment_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
		delivery_run_id TEXT NOT NULL,
		obligation_id TEXT NOT NULL REFERENCES progress_delivery_obligations(obligation_id) ON DELETE CASCADE,
		semantic_identity TEXT NOT NULL,
		attempt_record_id TEXT NOT NULL REFERENCES progress_delivery_attempts(attempt_record_id) ON DELETE CASCADE,
		attempt_ordinal INTEGER NOT NULL,
		result_record_id TEXT NOT NULL REFERENCES progress_delivery_attempt_results(result_record_id) ON DELETE CASCADE,
		claim_owner TEXT NOT NULL,
		claim_generation INTEGER NOT NULL,
		transport_contract TEXT NOT NULL,
		provider_idempotency_key TEXT NOT NULL,
		evidence_kind TEXT NOT NULL,
		evidence_ref TEXT NOT NULL,
		evidence_json TEXT NOT NULL,
		acknowledged_at TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(attempt_ordinal > 0),
		CHECK(claim_generation > 0),
		CHECK(json_valid(evidence_json)),
		CHECK(json_valid(payload_json)),
		UNIQUE(project_id, delivery_run_id, semantic_identity)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_progress_delivery_acknowledgments_obligation
		ON progress_delivery_acknowledgments(project_id, delivery_run_id, obligation_id)`,

	`CREATE TABLE IF NOT EXISTS progress_delivery_replay_cursors (
		cursor_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
		delivery_run_id TEXT NOT NULL,
		origin_kind TEXT NOT NULL,
		origin_id TEXT NOT NULL,
		obligation_id TEXT NOT NULL REFERENCES progress_delivery_obligations(obligation_id) ON DELETE CASCADE,
		claim_owner TEXT NOT NULL,
		claim_generation INTEGER NOT NULL,
		cursor_value TEXT NOT NULL,
		advanced_at TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(claim_generation > 0),
		CHECK(json_valid(payload_json)),
		UNIQUE(project_id, delivery_run_id, origin_kind, origin_id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_progress_delivery_replay_cursors_obligation
		ON progress_delivery_replay_cursors(project_id, delivery_run_id, obligation_id)`,
}
