package storage

var providerInventorySchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS adapter_declarations (
		adapter_declaration_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		adapter_id TEXT NOT NULL,
		adapter_version TEXT NOT NULL,
		display_name TEXT NOT NULL DEFAULT '',
		executable_names_json TEXT NOT NULL DEFAULT '[]',
		created_at TEXT NOT NULL DEFAULT '',
		updated_at TEXT NOT NULL DEFAULT '',
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(executable_names_json)),
		CHECK(json_valid(payload_json))
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_adapter_declarations_adapter_version ON adapter_declarations(adapter_id, adapter_version)`,
	`CREATE TABLE IF NOT EXISTS provider_installations (
		provider_installation_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL,
		scope TEXT NOT NULL,
		project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
		adapter_id TEXT NOT NULL,
		adapter_declaration_id TEXT NOT NULL,
		provider_display_name TEXT NOT NULL,
		executable_name TEXT NOT NULL,
		executable_identity_json TEXT NOT NULL,
		canonical_path TEXT NOT NULL DEFAULT '',
		canonical_path_redacted TEXT NOT NULL,
		discovery_source TEXT NOT NULL,
		discovery_order INTEGER NOT NULL,
		platform TEXT NOT NULL,
		version TEXT NOT NULL DEFAULT '',
		version_confidence TEXT NOT NULL,
		latest_probe_result_id TEXT,
		installation_state TEXT NOT NULL,
		usable_for_invocation TEXT NOT NULL,
		known_limitations_json TEXT NOT NULL DEFAULT '[]',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		created_by_json TEXT NOT NULL DEFAULT '{}',
		updated_by_json TEXT NOT NULL DEFAULT '{}',
		host_json TEXT NOT NULL DEFAULT '{}',
		policy_version TEXT NOT NULL DEFAULT '',
		captured_at TEXT NOT NULL,
		stale_after TEXT NOT NULL DEFAULT '',
		freshness_state TEXT NOT NULL,
		confidence TEXT NOT NULL,
		side_effect_class TEXT NOT NULL,
		classification TEXT NOT NULL,
		source_json TEXT NOT NULL DEFAULT '{}',
		evidence_json TEXT NOT NULL DEFAULT '{}',
		gap_reasons_json TEXT NOT NULL DEFAULT '[]',
		terminal_error_code TEXT NOT NULL DEFAULT '',
		payload_json TEXT NOT NULL,
		CHECK(json_valid(executable_identity_json)),
		CHECK(json_valid(known_limitations_json)),
		CHECK(json_valid(created_by_json)),
		CHECK(json_valid(updated_by_json)),
		CHECK(json_valid(host_json)),
		CHECK(json_valid(source_json)),
		CHECK(json_valid(evidence_json)),
		CHECK(json_valid(gap_reasons_json)),
		CHECK(json_valid(payload_json))
	)`,
	`CREATE INDEX IF NOT EXISTS idx_provider_installations_adapter_state ON provider_installations(adapter_id, installation_state)`,
	`CREATE INDEX IF NOT EXISTS idx_provider_installations_latest_probe ON provider_installations(latest_probe_result_id)`,
	`CREATE TABLE IF NOT EXISTS provider_probe_results (
		probe_result_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL,
		scope TEXT NOT NULL DEFAULT 'machine',
		project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
		adapter_id TEXT NOT NULL,
		adapter_declaration_id TEXT NOT NULL,
		provider_installation_id TEXT REFERENCES provider_installations(provider_installation_id) ON DELETE SET NULL,
		probe_kind TEXT NOT NULL,
		probe_command_id TEXT NOT NULL DEFAULT '',
		probe_method TEXT NOT NULL,
		outcome TEXT NOT NULL,
		timeout_ms INTEGER NOT NULL,
		stdout_limit_bytes INTEGER NOT NULL,
		stderr_limit_bytes INTEGER NOT NULL,
		combined_output_limit_bytes INTEGER NOT NULL,
		exit_code INTEGER,
		timed_out INTEGER NOT NULL,
		killed INTEGER NOT NULL,
		network_declared INTEGER NOT NULL,
		network_permission TEXT NOT NULL,
		secret_finding_count INTEGER NOT NULL,
		created_at TEXT NOT NULL DEFAULT '',
		updated_at TEXT NOT NULL DEFAULT '',
		created_by_json TEXT NOT NULL DEFAULT '{}',
		updated_by_json TEXT NOT NULL DEFAULT '{}',
		host_json TEXT NOT NULL DEFAULT '{}',
		policy_version TEXT NOT NULL DEFAULT '',
		captured_at TEXT NOT NULL,
		freshness_state TEXT NOT NULL,
		confidence TEXT NOT NULL,
		terminal_error_code TEXT NOT NULL DEFAULT '',
		payload_json TEXT NOT NULL,
		CHECK(json_valid(created_by_json)),
		CHECK(json_valid(updated_by_json)),
		CHECK(json_valid(host_json)),
		CHECK(json_valid(payload_json))
	)`,
	`CREATE INDEX IF NOT EXISTS idx_provider_probe_results_adapter_captured ON provider_probe_results(adapter_id, captured_at)`,
	`CREATE INDEX IF NOT EXISTS idx_provider_probe_results_installation ON provider_probe_results(provider_installation_id)`,
	`CREATE TABLE IF NOT EXISTS account_profiles (
		account_profile_id TEXT PRIMARY KEY,
		adapter_id TEXT NOT NULL,
		provider_installation_id TEXT REFERENCES provider_installations(provider_installation_id) ON DELETE SET NULL,
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(payload_json))
	)`,
	`CREATE TABLE IF NOT EXISTS auth_readiness (
		auth_readiness_id TEXT PRIMARY KEY,
		adapter_id TEXT NOT NULL,
		provider_installation_id TEXT REFERENCES provider_installations(provider_installation_id) ON DELETE SET NULL,
		account_profile_id TEXT REFERENCES account_profiles(account_profile_id) ON DELETE SET NULL,
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(payload_json))
	)`,
	`CREATE TABLE IF NOT EXISTS model_catalog_snapshots (
		model_catalog_snapshot_id TEXT PRIMARY KEY,
		adapter_id TEXT NOT NULL,
		provider_installation_id TEXT REFERENCES provider_installations(provider_installation_id) ON DELETE SET NULL,
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(payload_json))
	)`,
	`CREATE TABLE IF NOT EXISTS model_capabilities (
		model_capability_id TEXT PRIMARY KEY,
		model_catalog_snapshot_id TEXT REFERENCES model_catalog_snapshots(model_catalog_snapshot_id) ON DELETE CASCADE,
		adapter_id TEXT NOT NULL,
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(payload_json))
	)`,
	`CREATE TABLE IF NOT EXISTS inventory_events (
		inventory_event_id TEXT PRIMARY KEY,
		event_hash TEXT NOT NULL,
		previous_event_hash TEXT NOT NULL DEFAULT '',
		project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
		event_kind TEXT NOT NULL,
		payload_hash TEXT NOT NULL,
		created_at TEXT NOT NULL,
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(payload_json))
	)`,
}
