package storage

var routingDecisionSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS routing_decisions (
		routing_decision_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT NOT NULL REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		task_id TEXT NOT NULL,
		task_requirement_id TEXT NOT NULL,
		decision_key TEXT NOT NULL,
		decision_kind TEXT NOT NULL,
		routing_policy_profile_id TEXT NOT NULL,
		role_definition_id TEXT NOT NULL DEFAULT '',
		plan_fingerprint TEXT NOT NULL,
		policy_fingerprint TEXT NOT NULL,
		routing_fingerprint TEXT NOT NULL,
		candidate_generation_status TEXT NOT NULL,
		decision_status TEXT NOT NULL,
		chosen_candidate_id TEXT NOT NULL DEFAULT '',
		terminal_error_code TEXT NOT NULL DEFAULT '',
		input_record_refs_json TEXT NOT NULL DEFAULT '[]',
		eligible_candidates_json TEXT NOT NULL DEFAULT '[]',
		rejected_candidates_json TEXT NOT NULL DEFAULT '[]',
		scored_candidates_json TEXT NOT NULL DEFAULT '[]',
		alternatives_json TEXT NOT NULL DEFAULT '[]',
		rejected_summary_json TEXT NOT NULL DEFAULT '{}',
		optimization_policy_json TEXT NOT NULL DEFAULT '{}',
		payload_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		decided_by_json TEXT NOT NULL,
		host_json TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(json_valid(input_record_refs_json)),
		CHECK(json_valid(eligible_candidates_json)),
		CHECK(json_valid(rejected_candidates_json)),
		CHECK(json_valid(scored_candidates_json)),
		CHECK(json_valid(alternatives_json)),
		CHECK(json_valid(rejected_summary_json)),
		CHECK(json_valid(optimization_policy_json)),
		CHECK(json_valid(payload_json)),
		CHECK(json_valid(decided_by_json)),
		CHECK(json_valid(host_json)),
		UNIQUE(project_id, delivery_run_id, decision_key, routing_fingerprint)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_routing_decisions_run_task ON routing_decisions(project_id, delivery_run_id, task_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS idx_routing_decisions_policy ON routing_decisions(routing_policy_profile_id, policy_fingerprint, decision_status)`,
	`CREATE INDEX IF NOT EXISTS idx_routing_decisions_chosen ON routing_decisions(chosen_candidate_id)`,
}
