package storage

var routingPolicyProfileSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS role_definitions (
		role_definition_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		role_key TEXT NOT NULL,
		role_version TEXT NOT NULL,
		policy_version TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		payload_fingerprint TEXT NOT NULL,
		provenance_json TEXT NOT NULL DEFAULT '{}',
		created_at TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(json_valid(payload_json)),
		CHECK(json_valid(provenance_json)),
		UNIQUE(role_key, role_version, policy_version)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_role_definitions_key ON role_definitions(role_key, role_version, policy_version)`,
	`CREATE TABLE IF NOT EXISTS routing_policy_profiles (
		routing_policy_profile_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		profile_key TEXT NOT NULL,
		profile_version TEXT NOT NULL,
		policy_version TEXT NOT NULL,
		policy_fingerprint TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		provenance_json TEXT NOT NULL,
		effective_from TEXT NOT NULL,
		supersedes_profile_id TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(json_valid(payload_json)),
		CHECK(json_valid(provenance_json)),
		UNIQUE(profile_key, profile_version, policy_version)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_routing_policy_profiles_key ON routing_policy_profiles(profile_key, profile_version, effective_from)`,
	`CREATE INDEX IF NOT EXISTS idx_routing_policy_profiles_fingerprint ON routing_policy_profiles(policy_fingerprint)`,
	`CREATE TABLE IF NOT EXISTS routing_policy_inputs (
		routing_policy_input_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		input_kind TEXT NOT NULL,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		routing_policy_profile_id TEXT NOT NULL,
		policy_fingerprint TEXT NOT NULL,
		scope TEXT NOT NULL,
		reason TEXT NOT NULL,
		status TEXT NOT NULL,
		expires_at TEXT NOT NULL DEFAULT '',
		constraint_json TEXT NOT NULL,
		validation_status TEXT NOT NULL,
		diagnostics_json TEXT NOT NULL DEFAULT '[]',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		actor_json TEXT NOT NULL,
		host_json TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		CHECK(input_kind IN ('pin', 'exclusion')),
		CHECK(record_version > 0),
		CHECK(json_valid(constraint_json)),
		CHECK(json_valid(diagnostics_json)),
		CHECK(json_valid(actor_json)),
		CHECK(json_valid(host_json)),
		CHECK(json_valid(payload_json))
	)`,
	`CREATE INDEX IF NOT EXISTS idx_routing_policy_inputs_scope ON routing_policy_inputs(project_id, delivery_run_id, routing_policy_profile_id, input_kind, status)`,
	`CREATE TABLE IF NOT EXISTS routing_legacy_model_mappings (
		legacy_model_mapping_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id),
		role_key TEXT NOT NULL,
		legacy_provider TEXT NOT NULL,
		legacy_model TEXT NOT NULL,
		legacy_reasoning_effort TEXT NOT NULL DEFAULT '',
		mapping_status TEXT NOT NULL,
		mapped_adapter_id TEXT NOT NULL DEFAULT '',
		mapped_model_capability_id TEXT NOT NULL DEFAULT '',
		diagnostic_code TEXT NOT NULL DEFAULT '',
		diagnostic TEXT NOT NULL DEFAULT '',
		policy_fingerprint TEXT NOT NULL DEFAULT '',
		payload_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		CHECK(mapping_status IN ('mapped', 'unresolved')),
		CHECK(json_valid(payload_json)),
		UNIQUE(project_id, role_key, legacy_provider, legacy_model, legacy_reasoning_effort)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_routing_legacy_model_mappings_status ON routing_legacy_model_mappings(project_id, mapping_status, role_key)`,
	`CREATE TABLE IF NOT EXISTS routing_events (
		routing_event_id TEXT PRIMARY KEY,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		event_kind TEXT NOT NULL,
		routing_policy_profile_id TEXT NOT NULL DEFAULT '',
		routing_fingerprint TEXT NOT NULL DEFAULT '',
		payload_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		CHECK(json_valid(payload_json))
	)`,
	`CREATE INDEX IF NOT EXISTS idx_routing_events_run ON routing_events(project_id, delivery_run_id, created_at)`,
}
