package storage

var taskRequirementSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS task_requirements (
		task_requirement_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		task_requirement_fingerprint TEXT NOT NULL,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT NOT NULL REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		task_id TEXT NOT NULL REFERENCES delivery_tasks(task_id) ON DELETE CASCADE,
		task_key TEXT NOT NULL,
		role_key TEXT NOT NULL,
		risk_tier TEXT NOT NULL,
		permission_required TEXT NOT NULL,
		side_effect_class TEXT NOT NULL,
		required_output TEXT NOT NULL,
		scope_json TEXT NOT NULL,
		data_classification TEXT NOT NULL,
		network_required TEXT NOT NULL,
		nested_allowed INTEGER NOT NULL,
		cancellation_required INTEGER NOT NULL,
		quality_floor TEXT NOT NULL,
		classification_rules_json TEXT NOT NULL DEFAULT '[]',
		required_capabilities_json TEXT NOT NULL DEFAULT '[]',
		verification_requirements_json TEXT NOT NULL DEFAULT '[]',
		heuristics_json TEXT NOT NULL DEFAULT '[]',
		provenance_summary TEXT NOT NULL,
		policy_version TEXT NOT NULL,
		plan_fingerprint TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		created_by_json TEXT NOT NULL,
		updated_by_json TEXT NOT NULL,
		host_json TEXT NOT NULL,
		classification TEXT NOT NULL,
		confidence TEXT NOT NULL,
		source_json TEXT NOT NULL DEFAULT '{}',
		heuristic INTEGER NOT NULL,
		heuristic_reason TEXT NOT NULL DEFAULT '',
		terminal_error_code TEXT NOT NULL DEFAULT '',
		gap_reasons_json TEXT NOT NULL DEFAULT '[]',
		payload_json TEXT NOT NULL,
		CHECK(json_valid(scope_json)),
		CHECK(json_valid(classification_rules_json)),
		CHECK(json_valid(required_capabilities_json)),
		CHECK(json_valid(verification_requirements_json)),
		CHECK(json_valid(heuristics_json)),
		CHECK(json_valid(created_by_json)),
		CHECK(json_valid(updated_by_json)),
		CHECK(json_valid(host_json)),
		CHECK(json_valid(source_json)),
		CHECK(json_valid(gap_reasons_json)),
		CHECK(json_valid(payload_json)),
		UNIQUE(project_id, delivery_run_id, task_id, plan_fingerprint)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_task_requirements_run_risk ON task_requirements(delivery_run_id, risk_tier)`,
	`CREATE INDEX IF NOT EXISTS idx_task_requirements_policy ON task_requirements(policy_version, plan_fingerprint)`,
	`CREATE TABLE IF NOT EXISTS task_requirement_overrides (
		requirement_override_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		task_id TEXT REFERENCES delivery_tasks(task_id) ON DELETE CASCADE,
		task_key TEXT NOT NULL DEFAULT '',
		plan_fingerprint TEXT NOT NULL DEFAULT '',
		scope_key TEXT NOT NULL,
		field TEXT NOT NULL,
		value_json TEXT NOT NULL,
		justification TEXT NOT NULL,
		status TEXT NOT NULL,
		validation_status TEXT NOT NULL,
		validation_error_code TEXT NOT NULL DEFAULT '',
		input_requirement_fingerprint TEXT NOT NULL DEFAULT '',
		output_requirement_fingerprint TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		created_by_json TEXT NOT NULL,
		updated_by_json TEXT NOT NULL,
		host_json TEXT NOT NULL,
		policy_version TEXT NOT NULL,
		classification TEXT NOT NULL,
		side_effect_class TEXT NOT NULL,
		confidence TEXT NOT NULL,
		source_json TEXT NOT NULL DEFAULT '{}',
		terminal_error_code TEXT NOT NULL DEFAULT '',
		gap_reasons_json TEXT NOT NULL DEFAULT '[]',
		payload_json TEXT NOT NULL,
		CHECK(json_valid(value_json)),
		CHECK(json_valid(created_by_json)),
		CHECK(json_valid(updated_by_json)),
		CHECK(json_valid(host_json)),
		CHECK(json_valid(source_json)),
		CHECK(json_valid(gap_reasons_json)),
		CHECK(json_valid(payload_json))
	)`,
	`CREATE INDEX IF NOT EXISTS idx_task_requirement_overrides_scope ON task_requirement_overrides(project_id, delivery_run_id, task_key, plan_fingerprint, status)`,
}
