package storage

var usageLedgerSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS usage_records (
		usage_record_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT REFERENCES projects(id) ON DELETE RESTRICT,
		delivery_run_id TEXT,
		task_id TEXT NOT NULL DEFAULT '',
		attempt_id TEXT NOT NULL DEFAULT '',
		worker_id TEXT NOT NULL DEFAULT '',
		sub_agent_id TEXT NOT NULL DEFAULT '',
		adapter_id TEXT NOT NULL DEFAULT '',
		account_profile_id TEXT,
		model_capability_id TEXT,
		event_kind TEXT NOT NULL,
		event_time TEXT NOT NULL,
		quantity_kind TEXT NOT NULL,
		value INTEGER NOT NULL,
		unit TEXT NOT NULL,
		value_scale INTEGER NOT NULL DEFAULT 0,
		confidence TEXT NOT NULL,
		freshness_state TEXT NOT NULL,
		source_kind TEXT NOT NULL,
		idempotency_key TEXT NOT NULL,
		dedupe_key TEXT NOT NULL DEFAULT '',
		replaces_usage_record_id TEXT,
		retain_until TEXT NOT NULL DEFAULT '',
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(payload_json))
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_records_idempotency ON usage_records(idempotency_key)`,
	`CREATE INDEX IF NOT EXISTS idx_usage_records_project_scope ON usage_records(project_id, delivery_run_id, task_id, worker_id, sub_agent_id)`,
	`CREATE INDEX IF NOT EXISTS idx_usage_records_provider_scope ON usage_records(adapter_id, account_profile_id, model_capability_id)`,
	`CREATE INDEX IF NOT EXISTS idx_usage_records_quantity_time ON usage_records(quantity_kind, event_time)`,
	`CREATE INDEX IF NOT EXISTS idx_usage_records_confidence ON usage_records(confidence, freshness_state)`,
	`CREATE TABLE IF NOT EXISTS usage_reconciliations (
		usage_reconciliation_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT REFERENCES projects(id) ON DELETE RESTRICT,
		provider_snapshot_id TEXT NOT NULL DEFAULT '',
		scope_key TEXT NOT NULL,
		quantity_kind TEXT NOT NULL,
		window_kind TEXT NOT NULL,
		window_start TEXT NOT NULL DEFAULT '',
		window_end TEXT NOT NULL DEFAULT '',
		local_total INTEGER NOT NULL,
		provider_total INTEGER,
		delta INTEGER,
		delta_confidence TEXT NOT NULL,
		outcome TEXT NOT NULL,
		idempotency_key TEXT NOT NULL,
		event_time TEXT NOT NULL,
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(payload_json))
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_reconciliations_idempotency ON usage_reconciliations(idempotency_key)`,
	`CREATE INDEX IF NOT EXISTS idx_usage_reconciliations_project_scope ON usage_reconciliations(project_id, scope_key, quantity_kind, window_kind)`,
	`CREATE TABLE IF NOT EXISTS usage_cleanup_events (
		usage_cleanup_event_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		project_id TEXT REFERENCES projects(id) ON DELETE RESTRICT,
		record_type TEXT NOT NULL,
		record_ids_json TEXT NOT NULL DEFAULT '[]',
		outcome TEXT NOT NULL,
		retention_rule TEXT NOT NULL,
		event_time TEXT NOT NULL,
		payload_json TEXT NOT NULL DEFAULT '{}',
		CHECK(json_valid(record_ids_json)),
		CHECK(json_valid(payload_json))
	)`,
}
