package storage

var verificationDecisionSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS verification_decisions (
		verification_decision_id TEXT PRIMARY KEY,
		schema_version TEXT NOT NULL,
		record_version INTEGER NOT NULL DEFAULT 1,
		project_id TEXT NOT NULL REFERENCES projects(id),
		delivery_run_id TEXT NOT NULL REFERENCES delivery_runs(delivery_run_id) ON DELETE CASCADE,
		task_id TEXT NOT NULL,
		task_requirement_id TEXT NOT NULL REFERENCES task_requirements(task_requirement_id) ON DELETE CASCADE,
		worker_routing_decision_id TEXT NOT NULL REFERENCES routing_decisions(routing_decision_id) ON DELETE CASCADE,
		verifier_routing_decision_id TEXT NOT NULL DEFAULT '',
		decision_key TEXT NOT NULL,
		idempotency_key TEXT NOT NULL,
		decision_status TEXT NOT NULL,
		verdict TEXT NOT NULL,
		required_independence TEXT NOT NULL,
		actual_independence TEXT NOT NULL,
		final_authority TEXT NOT NULL,
		final_authority_fingerprint TEXT NOT NULL,
		terminal_error_code TEXT NOT NULL DEFAULT '',
		verification_fingerprint TEXT NOT NULL,
		policy_fingerprint TEXT NOT NULL,
		plan_fingerprint TEXT NOT NULL,
		disagreements_json TEXT NOT NULL DEFAULT '[]',
		evidence_refs_json TEXT NOT NULL DEFAULT '[]',
		council_json TEXT NOT NULL DEFAULT '{}',
		payload_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		decided_by_json TEXT NOT NULL,
		host_json TEXT NOT NULL,
		CHECK(record_version > 0),
		CHECK(json_valid(disagreements_json)),
		CHECK(json_valid(evidence_refs_json)),
		CHECK(json_valid(council_json)),
		CHECK(json_valid(payload_json)),
		CHECK(json_valid(decided_by_json)),
		CHECK(json_valid(host_json)),
		UNIQUE(delivery_run_id, task_id, decision_key, idempotency_key)
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_verification_decisions_terminal_authority
		ON verification_decisions(delivery_run_id, task_id, decision_key, final_authority_fingerprint)
		WHERE decision_status IN ('accepted', 'rejected', 'needs-human')`,
	`CREATE INDEX IF NOT EXISTS idx_verification_decisions_run ON verification_decisions(project_id, delivery_run_id, task_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS idx_verification_decisions_worker ON verification_decisions(worker_routing_decision_id, decision_status)`,
	`CREATE INDEX IF NOT EXISTS idx_verification_decisions_status ON verification_decisions(decision_status, terminal_error_code)`,
	`CREATE TABLE IF NOT EXISTS verification_decision_members (
		verification_decision_id TEXT NOT NULL REFERENCES verification_decisions(verification_decision_id) ON DELETE CASCADE,
		member_ordinal INTEGER NOT NULL,
		member_id TEXT NOT NULL DEFAULT '',
		routing_decision_id TEXT NOT NULL REFERENCES routing_decisions(routing_decision_id) ON DELETE RESTRICT,
		routing_candidate_id TEXT NOT NULL,
		routing_fingerprint TEXT NOT NULL,
		candidate_fingerprint TEXT NOT NULL,
		actual_independence TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		PRIMARY KEY(verification_decision_id, member_ordinal),
		UNIQUE(verification_decision_id, routing_decision_id),
		UNIQUE(verification_decision_id, routing_candidate_id),
		UNIQUE(verification_decision_id, routing_fingerprint),
		CHECK(member_ordinal >= 0),
		CHECK(json_valid(payload_json))
	)`,
	`CREATE INDEX IF NOT EXISTS idx_verification_decision_members_route ON verification_decision_members(routing_decision_id)`,
}
